# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(339, 488)
        MainWindow.setMinimumSize(QtCore.QSize(339, 488))
        MainWindow.setMaximumSize(QtCore.QSize(999, 999999))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayout = QtGui.QFormLayout(self.centralwidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(56, 3))
        self.line.setMaximumSize(QtCore.QSize(56, 3))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.line.setFont(font)
        self.line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.title_label = QtGui.QLabel(self.centralwidget)
        self.title_label.setMinimumSize(QtCore.QSize(181, 33))
        self.title_label.setMaximumSize(QtCore.QSize(181, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Open Sans"))
        font.setPointSize(18)
        self.title_label.setFont(font)
        self.title_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.title_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setWordWrap(False)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.horizontalLayout.addWidget(self.title_label)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setMinimumSize(QtCore.QSize(56, 3))
        self.line_2.setMaximumSize(QtCore.QSize(56, 3))
        self.line_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(
            305, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.thread_table = QtGui.QTableWidget(self.centralwidget)
        self.thread_table.setMinimumSize(QtCore.QSize(305, 186))
        self.thread_table.setMaximumSize(QtCore.QSize(305, 186))
        self.thread_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thread_table.setFrameShape(QtGui.QFrame.StyledPanel)
        self.thread_table.setFrameShadow(QtGui.QFrame.Sunken)
        self.thread_table.setObjectName(_fromUtf8("thread_table"))
        self.thread_table.setColumnCount(0)
        self.thread_table.setRowCount(0)
        self.verticalLayout.addWidget(self.thread_table)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.start_button = QtGui.QPushButton(self.centralwidget)
        self.start_button.setMinimumSize(QtCore.QSize(150, 22))
        self.start_button.setMaximumSize(QtCore.QSize(150, 22))
        self.start_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.horizontalLayout_2.addWidget(self.start_button)
        self.stop_button = QtGui.QPushButton(self.centralwidget)
        self.stop_button.setMinimumSize(QtCore.QSize(149, 22))
        self.stop_button.setMaximumSize(QtCore.QSize(149, 22))
        self.stop_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.horizontalLayout_2.addWidget(self.stop_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(152, 23))
        self.label.setMaximumSize(QtCore.QSize(152, 23))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label.setFrameShadow(QtGui.QFrame.Sunken)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.searching_number = QtGui.QLCDNumber(self.centralwidget)
        self.searching_number.setMinimumSize(QtCore.QSize(151, 23))
        self.searching_number.setMaximumSize(QtCore.QSize(151, 23))
        self.searching_number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searching_number.setFrameShape(QtGui.QFrame.StyledPanel)
        self.searching_number.setFrameShadow(QtGui.QFrame.Sunken)
        self.searching_number.setObjectName(_fromUtf8("searching_number"))
        self.horizontalLayout_3.addWidget(self.searching_number)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(51, 136))
        self.label_2.setMaximumSize(QtCore.QSize(51, 136))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.result_label = QtGui.QTextBrowser(self.centralwidget)
        self.result_label.setMinimumSize(QtCore.QSize(256, 136))
        self.result_label.setMaximumSize(QtCore.QSize(256, 136))
        self.result_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.result_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.result_label.setObjectName(_fromUtf8("result_label"))
        self.horizontalLayout_4.addWidget(self.result_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.formLayout.setLayout(
            0, QtGui.QFormLayout.LabelRole, self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.title_label.setText(_translate(
            "MainWindow", "Prime Processor", None))
        self.start_button.setText(_translate("MainWindow", "Start", None))
        self.stop_button.setText(_translate("MainWindow", "Stop", None))
        self.label.setText(_translate(
            "MainWindow", "Searching number :", None))
        self.label_2.setText(_translate("MainWindow", "Result : ", None))
